// <auto-generated />
using CItyInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CItyInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CItyInfo.API.Entity.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Centre of Excellence",
                            Name = "Lagos"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Heart Beat of the Nation",
                            Name = "Edo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Big Heart",
                            Name = "Delta"
                        });
                });

            modelBuilder.Entity("CItyInfo.API.Entity.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "High Rise Buildings and Water Log",
                            Name = "Island"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Capital City of the State",
                            Name = "Mainland"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Capital City of the State",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Home Town",
                            Name = "Esan"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Capital City of the State",
                            Name = "Asaba"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "Oil Rich Region",
                            Name = "Warri"
                        });
                });

            modelBuilder.Entity("CItyInfo.API.Entity.PointOfInterest", b =>
                {
                    b.HasOne("CItyInfo.API.Entity.City", "City")
                        .WithMany("PointOfInterests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CItyInfo.API.Entity.City", b =>
                {
                    b.Navigation("PointOfInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
